python train.py \
    --domain neorl \
    --task Hopper-v3 \
    --data-type low \
    --episode-len 1000 \
    --discount 1. \
    --survival-reward True \
    --improve-step 20 \
    --pref-num 15 \
    --pref-max-iters 10 \
    --select-num 300 \
    --threshold 1.05 \
    --weight-decay 2e-4